apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-health-check
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-check
            image: curlimages/curl:latest
            command: ["/bin/sh"]
            args: ["-c", "curl -s http://todoapp-service:80/api/health"]
            resources:
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "200m"
                memory: "200Mi"
          restartPolicy: OnFailure 